# Generated by Django 3.2.6 on 2021-08-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx_clone', '0007_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_product/'),
        ),
    ]
